apiVersion: v1
kind: Secret
metadata:
  name: data-secret
type: Opaque
data:
  MYSQL_ALLOW_EMPTY_PASSWORD: eWVz
  MYSQL_DATABASE: bXlkYXRhYmFzZQ==
  MYSQL_PASSWORD: cm9vdA==
  MYSQL_ROOT_PASSWORD: cm9vdA==
  MYSQL_DB_HOST: ZGF0YQ==
  MYSQL_USER_PASSWORD: cm9vdA== 
  MYSQL_USER: cm9vdA==         
