version: "3"
services:

  front:
    image: anat777/quotes-front
    ports:
      - "3001:3001"
    networks:
      - myapp

  back:
    image: anat777/quotes-back
    ports:
      - "3000:3000"
    networks:
      - myapp

  data:
    image: anat777/quotes-data
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "mydatabase"
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - myapp

  data-script:
    image: anat777/quotes-data-script  
    networks:
      - myapp
