apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: aws
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  zones: us-east-1a
  iopsPerGB: "10"
  encrypted: "false"
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
  - debug
volumeBindingMode: Immediate
