apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    io.kompose.service: data
spec:
  ports:
  - port: 3306
    name: data
  clusterIP: None
  selector:
    io.kompose.service: data

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.20.0 (f3d54d784)
  labels:
    io.kompose.service: data
  name: data
spec:
  replicas: 1
  serviceName: "api"
  selector:
    matchLabels:
      io.kompose.network/myapp: "true"
      io.kompose.service: data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 1Gi
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.20.0 (f3d54d784)
      creationTimestamp: null
      labels:
        io.kompose.network/myapp: "true"
        io.kompose.service: data
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - image: anat777/quotes-data:v1
        name: data
        args:
        - "--ignore-db-dir=lost+found"
        ports:
        - containerPort: 3306
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: data
        env:
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: data-secret
              key: MYSQL_ALLOW_EMPTY_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: data-secret
              key: MYSQL_DATABASE
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: data-secret
              key: MYSQL_PASSWORD
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: data-secret
              key: MYSQL_ROOT_PASSWORD
      restartPolicy: Always
